version: '3.9'
services:
  auth:
    tty: true
    volumes:
      # Маппим таким образом для того, чтобы фласка видела изменения в файлах
      # и перезапускала сервис
      - ./auth/src:/opt/app
    entrypoint: flask run --host 0.0.0.0 --port 8000 --debug
    profiles: ['dev']

  postgres:
    ports:
      - '5432:5432'
    profiles: ['dev']

  redis:
    ports:
      - '6379:6379'
    profiles: ['dev']

  rediscommander:
    container_name: rediscommander
    restart: on-failure
    image: rediscommander/redis-commander:latest
    ports:
      - '9000:8081'
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD
    networks:
      - redis
    profiles: ['dev']

  jaeger:
    container_name: jaeger
    restart: on-failure
    image: jaegertracing/all-in-one:1.44.0
    ports:
      - '16686:16686'
      - '6831:6831'
      - '4317:4317'
      - '4318:4318'
    environment:
      - QUERY_BASE_PATH=/admin/jaeger
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - nginx
      - auth
    profiles: ['dev']
