"""Add SocialAccount table

Revision ID: c6d4cb4740c0
Revises: dbc9d353c0e6
Create Date: 2023-04-24 12:56:29.328589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d4cb4740c0'
down_revision = 'dbc9d353c0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_id', sa.Text(), nullable=False),
    sa.Column('social_name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('social_id', 'social_name', name='social_pk'),
    schema='auth'
    )
    with op.batch_alter_table('devices', schema='auth') as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('roles', schema='auth') as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users_info', schema='auth') as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_info', schema='auth') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('roles', schema='auth') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('devices', schema='auth') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('social_account', schema='auth')
    # ### end Alembic commands ###
